on: push
name: CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.3
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install composer dependencies
        run: |
          composer install --no-scripts
      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
      - name: Create Database
        run: |
          mkdir -p database
          touch database/testdb.sqlite
      - name: Run Migration
        run: |
          php artisan migrate --database=sqlite
      - name: Run Testsuite
        run: vendor/bin/phpunit tests/
      - name: Deploy to Server
        run: curl ${{ secrets.FORGE_DEPLOYMENT_WEBHOOK }}
